version: "3"

services:
  app:
    image: webdevops/php-apache:7.4
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      WEB_DOCUMENT_ROOT: /srv/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "UTC"
    working_dir: /srv
    volumes:
      - .:/srv

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/srv
